spring:
  data:
    mongodb:
      uri: mongodb+srv://cluster0.9xontdn.mongodb.net/test?authMechanism=MONGODB-X509&authSource=%24external&tls=true&tlsCertificateKeyFile=E%3A%5CX509-cert-956921310671160450.pem
