spring:
  data:
    mongodb:
      data-api:
        base-url: https://eu-west-2.aws.data.mongodb-api.com/app/data-rieuu/endpoint/data/v1/action/
        api-key: tizotQWBLnkJEBYvvCKbJ8UA2McbB9BstP3WHy19Lx1XAZDFnz5Bl3RkonJKNAHz
        dataSource: Cluster0
        database: gameanalytics-project
        collection1: gamedata
        collection2: userdata

hearthstoneMiner:
  url: http://localhost:7373
